### ISSUE TITLE
Better loading behaviour

### ISSUE THREAD

**Issue by lucatume** [lucatume/local-addon-xdebug-control#2]
As reported by @soderlind [here](https://github.com/lucatume/local-addon-xdebug-control/issues/1#issuecomment-334945605) the initial state loading could be improved.  
The current behavior is to read the XDebub status and current settings from the container when switching to the XDebug Control tab, this can lead to a "dead" time where for 5 to 10 seconds nothing seems to happen after the click.
The idea would be to show the view immediately and lazy load the status, quite basic stuff that did not make it into the first version.

**Comment by lucatume** [comment]
Fixed in version `1.0.3`

**Comment by soderlind** [comment]
The loader screen makes it much better :) i "feels" faster.

**Comment by lucatume** [comment]
I'm a slow learner but I learn. Thanks for all your feedback.
