### ISSUE TITLE
Addon is not working with Local 2.1.1

### ISSUE THREAD

**Issue by ravinderk** [lucatume/local-addon-xdebug-control#3]
I following the same step as you described in `readme.md` file but I am getting an error while visiting addon setting page. Restart local machine after disable/enable addon but still getting same error.

<img width="1103" alt="screen shot 2017-11-07 at 11 30 00 am" src="https://user-images.githubusercontent.com/1784821/32479315-39428b56-c3af-11e7-81f8-a4541dd5717e.png">

**Comment by ravinderk** [comment]
With Local `2.1.2`, I am seeing a white screen.

<img width="1237" alt="screen shot 2017-11-20 at 8 10 55 am" src="https://user-images.githubusercontent.com/1784821/32999866-915163e2-cdca-11e7-9acd-0821ee3c5018.png">

**Comment by HRoger** [comment]
The same problem here.

**Comment by tekjc** [comment]
I'm getting this on Windows with 2.1.2.50:

![image](https://user-images.githubusercontent.com/22498882/34075649-80cdfc08-e29a-11e7-95a7-7f9a64335d42.png)

**Comment by ravinderk** [comment]
@lucatume Addon still not working for me. Let me know if I am missing something.

**Details**
OS: MacOS High Sierra
Local Flywheel:  `2.2.3`


![image](https://user-images.githubusercontent.com/1784821/36081615-2ce97d7e-0fc7-11e8-90e3-e6b13cc670b3.png)

**Comment by lucatume** [comment]
Could you try to refresh (⌘+R on Mac or Ctrl+R on Windows while focused on the Local app) and let me know if the machine status is updated?

**Comment by ravinderk** [comment]
@lucatume  it is not working for me.

**Comment by lucatume** [comment]
@ravinderk

**Comment by ravinderk** [comment]
@lucatume Thank you for reopening issue. I do not know what was causing at my end but maybe it cache related. I am not sure but after restarting the machine  it is working fine for me.
